### PR TITLE
Implement set

### LINKED ISSUE #24: Implement Set
Create a new struct `Set` that follows the interface `Collection` and implement a method `Add` that adds an element to the set.

If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you.

Please take a look at our [CONTRIBUTING.md](https://github.com/gopher-utils/go-collections/blob/main/CONTRIBUTING.md) before you start working on this.

### PR DESCRIPTION
**Pull request by zegabr**
### Description

Add Set implementation

### Related Issues

Closes #24 

### Checklist

- [x] I have tested this code.
- [x] I have reviewed the code changes.
- [x] I have updated the documentation.
- [x] This PR follows the coding standards.
- [x] I have added tests for the changes.

### CODE REVIEW

**Comment by zegabr** [comment]
I've implemented most of the methods I found on the List implementation. But as this is a Set implementation, what do you think of implementing some Set operations like:

Union(s1, s2) -> returns a new set as the union of both sets
Intersection(s1, s2) -> returns a new set with elements that exist in both sets
Disjunction(s1, s2) -> returns a new set with the elements that don't exist in both sets

**Comment by zegabr** [comment]
Another thing: Considering this [thread](https://github.com/golang/go/issues/52157#issuecomment-1098330894), as far as I understood, the `capacity` property on the map initializations don't guarantee it to be able to store as much as `capacity` elements without it being resized. So I omitted it from the Set initializations.

Let me know if you agree with that.

**Comment by adarsh-a-tw** [comment]
> I've implemented most of the methods I found on the List implementation. But as this is a Set implementation, what do you think of implementing some Set operations like:
> 
> Union(s1, s2) -> returns a new set as the union of both sets Intersection(s1, s2) -> returns a new set with elements that exist in both sets Disjunction(s1, s2) -> returns a new set with the elements that don't exist in both sets

That's a great idea. But, let's not bring it into this issue. We can create a separate issue for that.

**Review by adarsh-a-tw — APPROVED** [review]
LGTM ! @zegabr Thanks for your contribution. 

We can merge it once other codeowners approve it.

**Comment by zegabr** [comment]
> That's a great idea. But, let's not bring it into this issue. We can create a separate issue for that.

Got it. Feel free to also assign it to me :)

**Review by GopinathRakkiyannan — APPROVED** [review]

**Review by aswath-s-tw — APPROVED** [review]

**Pull request merged**
